### ISSUE TITLE
Separate stop / start features

### ISSUE THREAD

**Issue by mihai-le** [jelastic-jps/start-stop-scheduler#1]
Hi,

Do you think it's possible to separate the start / stop features offered by this add-on ? Or at least to also offer the stop procedure separately ? 

I submit this issue, because one of the customers wants to have the possibility to schedule the environment to  be stopped ( if the environment is running )at a specified time if he forgot to manually stop it without being started later. 

I will also work on this and get back to you once I have a new version of the current add-on with the above feature. 

Please let me know your opinion on the above modifications.

Regards,

Mihai Podina

**Comment by ihorman** [comment]
Hi Mihai, 

Please use recent version of manifest from trunk, in this version you can leave start field empty and addon will manage stop only, start will not be triggered. 
Thank you for  the feedback ;)

Best Regards,
Ihor
