### ISSUE TITLE
Broken installation with "Duplicate entry"

### ISSUE THREAD

**Issue by 5ika** [jelastic-jps/start-stop-scheduler#4]
On the first try, the installation failed with a `permission denied`. Then, every tries return this error:

```json
{"result":99
,"source":"hx-core",
"error":"org.hibernate.exception.ConstraintViolationException: (conn:96357) Duplicate entry 'instance-start-stop' for key 'f_name'",
"type":"error",
"message":"org.hibernate.exception.ConstraintViolationException: (conn:96357) Duplicate entry 'instance-start-stop' for key 'f_name'"}
``` 

But the add-on is never fully installed. Is it possible to remove the broken installation and start with a fresh one ?

**Comment by siruslan** [comment]
@5ika, thanks for the report. Can you provide details on your environment (env name and platform domain)? Our team will check it.

**Comment by siruslan** [comment]
Btw, you can also open console via https://app.{platform-domain}/console and find the related logs. They will help us to find out the root of the issue.

**Comment by 5ika** [comment]
Thanks for your response @siruslan. My plateform domain is hidora.com and my env name is crea1.hidora.com (Apache with custom docker image). The manipulation works for duplicate environments but not this one.

**Comment by siruslan** [comment]
@5ika, could you check it one more time? @dzotic9 recently committed related updates.

**Comment by 5ika** [comment]
It works. Thank you @dzotic9 @siruslan !
